name: OfTrees
favicon: null
layout_spectrum: 0.7272525257430971
typography_spectrum: 0.04576118499971926
cta:
  domain: null
  bucket: null
  version: null
analytics:
  google: null
  facebook: null
  twitter: null
opengraph:
  image: null
  type: null
  appId: null
color:
  brandColors:
    - '#ADD7F6'
    - '#87BFFF'
    - '#3F8EFC'
    - '#2667FF'
    - '#3B28CC'
  brandStrength: 0.39551871619187295
  lightness: 0.12702135741710663
  saturation: 0.04003798612393439
  rhythmicContrast: 0.3903872943483293
purpose: []
