name: OfTrees
favicon: null
layout_spectrum: 0.9137
typography_spectrum: 0.47564
cta:
  domain: null
  bucket: null
  version: null
analytics:
  google: null
  facebook: null
  twitter: null
opengraph:
  image: null
  type: null
  appId: null
color:
  brandColors:
    - '#070007'
    - '#f7efc0'
    - '#614321'
    - '#c16c33'
    - '#00af26'
  brandStrength: 0.5
  lightness: 0.5
  saturation: 0.125
  rhythmicContrast: 0.5
purpose: []
